---
title: "Law Citation Network"
author: "Yi Yin"
date: "4/21/2019"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r Setup, include=FALSE, results='hide', warning=FALSE}
library(knitr)
opts_chunk$set(fig.path="figures/",
               cache.path="cache/",
               cache=TRUE,
               echo=TRUE,
               message=FALSE,
               warning=FALSE)  
```  



```{r preamble, message=FALSE, warning=FALSE, include=FALSE}
rm(list = ls())
library(tidyverse)
```

```{r, include=FALSE}
cases<-read.csv("./cite_node159.csv", sep = ",", 
                row.names=1, 
                colClasses = 'character')
library(lubridate)
cases<-cases%>%
        mutate(name = str_replace(file_name,"\\d*\\s-\\s",""))

cases<-cases%>%
        mutate(id = row_number())

cases[86,'dates'] = '2012-09-21'

cases<-cases%>%
        mutate(date = as.Date(dates))

cases%>%filter(date>=as.Date(today()))%>%
        select(id, file_name)

cases[5,'date'] = as.Date('2013-09-04')
cases[12,'date'] = as.Date('2017-04-04')
cases[76,'date'] = as.Date('2014-05-09')
cases[90,'date'] = as.Date('2012-05-17')
cases[133,'date'] = as.Date('2013-06-18')

cases<-cases%>%select(case_number, name,  date, file_name)


# write.csv(cases, "meta.csv")
```

```{r, message=FALSE}
links <-read.csv("./cite_egde159.csv", sep = ",", row.names=1,
                 colClasses = 'character')
edges<-links%>%group_by(to)%>%summarise(freq=n())%>%
        arrange(desc(freq))%>%filter(freq>5)
links<- links%>%filter(to %in% edges$to)
rm(edges)

```


```{r, fig.align='center', fig.width=12, fig.height=12}
library("igraph")
net <- graph_from_data_frame(d=links, directed=T)

# plot(x=1:5, y=rep(5,5), pch=19, cex=12, 
#      col="#7F7F7F66", xlim=c(0,6))  
# 
# adjustcolor("gray50", alpha=.4)


vex <-tibble(node = rep(NA, length(V(net)$name)))%>%
        mutate(node = V(net)$name)
vex$indegree <- degree(net, mode = "in",normalized = T)
vex%>%arrange(desc(indegree))%>%top_n(3)

vex <-vex%>%mutate(label = ifelse(indegree >=0.1, node, NA))
vex <-vex%>%mutate(ncolor = ifelse(indegree >=0.1, 
                                   "#923740", '#8C9F2C'))





V(net)$color <-vex$ncolor
V(net)$label <-NA
V(net)$label.family <-"Palatino"
V(net)$label.color <-"#923740"
V(net)$label.cex <- 0.5
V(net)$label.degree<- pi/3
V(net)$label.dist <-0.5
V(net)$size <- vex$indegree*30

E(net)$width <- 0.6
E(net)$edge.color <- "#2C2D25"
E(net)$arrow.size <- 0.04


plot(net, layout=layout_with_kk(net))

vex%>%arrange(desc(indegree))%>%filter(indegree >=0.103)
```



